version: "3"
services:
  trainer:
    image: trainer:latest
    build:
      context: .
      dockerfile: docker/train/Dockerfile

  predict:
    image: predict:latest
    build:
      context: .
      dockerfile: docker/predict/Dockerfile
