version: "3"
services:
  trainer:
    image: trainer:latest
    build:
      context: .
      dockerfile: docker/train/Dockerfile

  api_streamlit:
    image: api_streamlit:latest
    build:
      context: .
      dockerfile: docker/api_streamlit/Dockerfile
    ports:
      - 8015:8015

  api_fastapi:
    image: api_fastapi:latest
    build:
      context: .
      dockerfile: docker/api_fastapi/Dockerfile
    ports:
      - 8000:8000
